### ISSUE TITLE
报错Key qiyi is missing in the map

### ISSUE THREAD

**Issue by Miaoshroom** [xihan123/AGE#112]
版本1.0.3![Screenshot_20240629_201222_cn.xihan.age.jpg](https://github.com/xihan123/AGE/assets/124256592/628d4f30-3881-441f-913e-ed32604564ee)

**Comment by xihan123** [comment]
本质上这个提示没有任何意义，只要视频正常加载无视就行

**Comment by Nekogugu** [comment]
> 本质上这个提示没有任何意义，只要视频正常加载无视就行

视频没有正常加载..

**Comment by Miaoshroom** [comment]
> 本质上这个提示没有任何意义，只要视频正常加载无视就行

晓得啦..
